#----------------------------网页信息----------------------------------
# site name
prefixName:  #小字
siteName: 
# favicon and site master avatar
favicon: https://pic.imgdb.cn/item/624aa2ca239250f7c5145d0d.png
avatar: https://unpkg.com/reverse-stu-allversions@1.0.0/img/202203071633899.gif
url: https://sakuraplus.c12th.cn/
description: 做自己喜欢做的事

# 左侧网站名称
logo:
  sakuraso: 
  no: Reverse
  shironeko: 

siteBuildingTime: 2022-05-06 21:10:00 # your site build time or founded date(2020-05-20 17:20:00)

#ICP备案信息尾部显示
icp:
  enable: true #选择性设置
  url: http://www.beian.miit.gov.cn/state/outPortal/loginPortal.action # 备案链接
  text:  # 备案信息

# cdn: 
pjax: 0 # 无刷新类似ajax,加速
mathjax: 1 # 1开启,公式解析

#-----------------------------导航栏--------------------------------
# 菜单导航栏
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  主站: { path: https://blog.c12th.cn , fa: fa-link faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    统计: {path: /analytics/ , fa: fa-line-chart },
    标签: {path: /tags, fa: fa-tags }, 
    # 技术: {path: /categories/技术/, fa: fa-code }, 
    # 生活: {path: /categories/生活/, fa: fa-file-text-o } #, 
    #资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    #随想: {path: /categories/随想/, fa: fa-commenting-o },
    #转载: {path: /categories/转载/, fa: fa-book }
  } }
  # 清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
  #   说说: {path: /artitalk/, fa: fa-commenting-o fa-commenting }, 
  #   相册: {path: /photos/, fa: fa-photo },
  #   悦读: {path: /books/, fa: fa-book },
  #   追剧: {path: /movies/, fa: fa-film faa-vertical }
  # } }
  # 留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  # 友人帐: { path: /links/, fa: fa-link faa-shake }
  # 赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /about/, fa: fa-leaf faa-wrench , submenus: { 
    # 我？: {path: /about/, fa: fa-meetup}, 
    # 主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    # Lab: {path: /lab/, fa: fa-cogs },
    # valine: {path: /valine/, fa: fa-cogs }
  } }
  #项目: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

#social  url, img PC端配置
social:
  gitee: {url: https://gitee.com/c12th, img: https://unpkg.com/reverse-stu-allversions@1.0.5/sakurapuls/img/gitee.png}
  github: {url: https://github.com/12thstan, img: https://unpkg.com/reverse-stu-allversions@1.0.5/sakurapuls/img/github.png}
  csdn: {url: https://blog.csdn.net/qq_39788788, img: https://unpkg.com/reverse-stu-allversions@1.0.5/sakurapuls/img/csdn.png}
  # zhihu: {url: https://www.zhihu.com/people/cungudafa, img: /img/social/zhihu.png}
  #jianshu: {url: /https://www.jianshu.com/u/9b726a534140, img: /img/social/jianshu.png}
  # sina: {url: http://weibo.com/3829198906/info, img: /img/social/sina.png}
  bilibili: {url: https://space.bilibili.com/28517585, img: https://unpkg.com/reverse-stu-allversions@1.0.5/sakurapuls/img/bilibili.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=447726912, img: https://unpkg.com/reverse-stu-allversions@1.0.5/sakurapuls/img/wangyiyun.png}
  # wechat: {url: /#, qrcode: /img/custom/cungudafa.png, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/12thstan, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/3829198906/info, fa: fa-weibo, color: dd4b39}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2627039020&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}
  csdn: {url: https://blog.csdn.net/qq_39788788, fa: fa-star, color: ff9900}

#--------------------------------首页----------------------------------------
# 首页轮播图蒙版
bgclass: filter-dot # 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
# 轮播图、如果文章没有设置photos会在这里随机取图
bg:
  - https://pic.imgdb.cn/item/624aa2ca239250f7c5145d1d.jpg
  - https://pic.imgdb.cn/item/624aa2ca239250f7c5145d18.jpg
  - https://pic.imgdb.cn/item/624aa2ca239250f7c5145d11.jpg
  - https://pic.imgdb.cn/item/624aa2ca239250f7c5145d09.jpg
  - https://pic.imgdb.cn/item/626e3242239250f7c515bad6.png
  - https://pic.imgdb.cn/item/626e3242239250f7c515bad1.jpg
  - https://pic.imgdb.cn/item/626e3242239250f7c515baca.jpg
  - https://img.afqaq.com/images/2022/03/10/dcd0aa28f3537f720adbdf7f9f0625b6_preview-00_00_00-00_00_30.gif

  # - https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.0.9/img/cover/(0).jpg.webp
  # - https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.0.9/img/cover/(1).jpg.webp
  # - https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.0.9/img/cover/(2).jpg.webp
  # - https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.0.9/img/cover/(3).jpg.webp
  # - https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.0.9/img/cover/(4).jpg.webp
  # - https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.0.9/img/cover/(5).jpg.webp
  # - https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.0.9/img/cover/(6).jpg.webp
  # - https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.0.9/img/cover/(7).jpg.webp

# 背景音乐
left_side_bar:
  enable: false

bg_music: https://cdn.jsdelivr.net/gh/cungudafa/cdn@latest/music/lovingstrangers.mp3

# 首页提示语
notice: 便利店营业时间 08:00 ~ 22:00
# 首页提示音
myvoice: # https://cdn.jsdelivr.net/gh/cungudafa/cdn@latest/music/lovingstrangers.mp3
# 缓加载动画
lazyloadImg: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/orange.progress-bar-stripe-loader.svg # https://cdn.jsdelivr.net/gh/cungudafa/cdn/img/loader/orange.progress-bar-stripe-loader.svg

# startdash url, title, desc img
startdash: 
  - {url: https://github.com/12thstan, title: Github, desc: , img: https://img.afqaq.com/images/2022/03/11/d148790fdff2be4cd1029ce0dafd050b_preview-00_00_00-00_00_30.gif}
  - {url: https://gitee.com/c12th, title: Gitee, desc: , img: https://img.afqaq.com/images/2022/03/11/f95defc7440e627c3e0029229245e860_preview-00_00_00-00_00_30.gif}
  - {url: https://space.bilibili.com/28517585, title: Bilibili, desc: , img: https://unpkg.com/reverse-stu-allversions@1.0.0/img/03.gif}

# 首页文章排序规则
# Home page sort type: -1: newer first，1: older first.首页文章排序规则
homePageSortType: -1
# Home page article shown number)首页最多显示文章数
homeArticleShown: 10


# 首页卡片显示文章描述
post_description:
  enable: true # 自动获取文章前50字


#--------------------------------功能页面-------------------------------------------
donate:
  title: 谢谢饲主了喵~
  message: 我能想到最浪漫的事，就是我喝奶茶你付钱~
  paypal: #https://www.paypal.me/hojuncn
  alipay: https://pic.imgdb.cn/item/624aa2db239250f7c51480ed.jpg #大图
  # alipayQR: /img/custom/donate/AliPayQR.jpg
  wechat: https://pic.imgdb.cn/item/624aa2db239250f7c51480f0.jpg #大图
  # wechatQR: /img/custom/donate/WeChanQR.jpg
  # wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://unpkg.com/reverse-stu-allversions@1.0.1/img # https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: iot 01.mp4 #Unbroken.mp4

aplayer:  ##媒体播放引擎，移动端会禁止自动播放
  enable: true
  id: 4989347813
  server: netease
  type: playlist
  fixed: true ##开启吸底模式，固定到底部
  autoplay: false ##音频自动播放
  loop: all  ##音频循环播放, 可选值: 'all', 'one', 'none'
  order: random ##音频循环顺序, 可选值: 'list', 'random'
  preload: auto ##预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 ##默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  mutex: true ##互斥，阻止多个播放器同时播放

# Valine ##极简留言功能
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
valine:
  enable: false ##打开valine评论功能true
  appId: 
  appKey: 
  notify: false #true自带评论mail回复提醒，第三方邮件提醒就设置为false
  verify: true #验证码
  visitor: true #统计阅读量
  comment_count: true #统计评论数
  avatar: monsterid # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: 之前评论被恶意刷了，现在重新开一个评论，大家文明留言哈~ # Comment Box placeholder
  requiredFields: ['nick','mail'] #设置必填项
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #输入框提示动画

# 动态说说页面
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://artitalk.js.org
artitalk:
  appID: 
  appKEY: 
  pageSize: 5 #每页显示说说的数量
  placeholder1: 写点啥呢 # 输入框提示语
  placeholder2: 要更新头像吗？ # 头像提示语
  severurl:  #国内版填写
  lang: zh #语言English(en)及西班牙语Español(es)
  motion: 0 # 加载动画1:加载,0取消加载
  bgimg: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich16.gif # 输入框小动画
  # 极简黑白主题minimalist、渐变主题gradient、壁纸wallpaper 
  # 参考 https://blog.csdn.net/cungudafa/article/details/106224223
  style: 
    enable: true #个性定制
    wallpaper: https://ae01.alicdn.com/kf/H21b5f6b8496141a1979a33666e1074d9x.jpg #https://bing.rthe.net/wallpaper  # 壁纸
    color: white   #字体颜色
    linear_gradient: rgba(255, 165, 150, 0.5) 5%, rgba(0, 228, 255, 0.35) 95% # 渐变规律颜色+百分比 rgb(109, 208, 242) 15%, rgb(245, 154, 190) 85%
    border_right_color: '#FFC0BE' #三角颜色
    animation: false #true打开动画渐变渲染(壁纸和动画渐变渲染建议只开一个)

# 评论 
gitalk:
  enable: false
  clientID:  #GitHub Application Client ID
  clientSecret:  #GitHub Application Client Secret
  repo: cungudafa.github.io  #博客的仓库名称(注意不是地址)
  owner: cungudafa #github用户名
  admin: cungudafa
  labels: 'gitalk' #github issue 对应的issue标签（新建一个）
  distractionFreeMode: true #无干扰模式，不需要更改


# 友链页信息,tips支持html语言
mylinkinfo:
  enable: true
  tips: '<p><strong>Tips:</strong>网站不要求https强制加锁，但头像图片尽量用安全链接哦！</p> <p style="font-size: 13px;color: #ff9999;"> 1. 请先 <font color=#ff1234 size=5>添加本站链接</font>，在本站留言，待站长审核通过即添加友链。<br>2. 拒绝广告站，技术博客优先~<br>3. 对于取消本站链接或死链，站长会定期移除。</p>'
  name: cungudafa
  desc: 一个学习记录者
  url: https://cungudafa.top
  img: https://cdn.jsdelivr.net/gh/cungudafa/cdn/img/custom/cungudafa.jpg

# botui https://www.bootcdn.cn/botui/
# 简介在about页面需要单独配置（/js/third-party/botui.js）

# books、movies页面使用的是豆瓣插件，在主题目录配置

# Whether to display post-calender in the `archive` page
# 设置在归档页面achive中是否显示'文章日历'控件
postCalendar: true 

# 仿volantis主题小标签美化 
# 更多详细使用参考 https://volantis.js.org/v2/tag-plugins/
# v_tags:
#   enable: true

#--------------------------------其他功能--------------------------------------------

# 简易信息聚合,站点共享
rss: /atom.xml

# Whether to activate the copyright information of the blog and author when copying the post content.
# minCharNumber: Approve copyright information by copying at least how many characters.
# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: true # 代码块是否可复制,true允许,false加上文章信息
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。

# 代码块相关
code:
  lang: true # 代码块是否显示名称
  copy: true # 代码块是否可复制
  shrink: true # 代码块是否可以收缩
  break: true # 代码是否折行

# 查看大图
fancybox:
  enable: true

# 外链转知乎卡片形式 
linkcard:
  enable: false #貌似和valine刷新有点冲突 ，排查中

# 需要下载hexo-worldcount是否开启字数统计 (可以在post设置no_word_count: true)
#不需要使用，直接设置值为false，或注释掉
word_count: true

# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次

# Add google analytics configuration
# 添加 Google Analytics 配置
googleAnalytics:
  enable: false
  id:

# Add baidu analytics configuration
# 添加 baidu Analytics 配置 https://tongji.baidu.com/
baiduAnalytics:
  enable: false # 百度分析
  id: 

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
  
# widgetpack 星星评分
# To get your ID visit https://widgetpack.com
widgetpack:
  enable: false #false
  id: 23889 #<app_id>
  color: fc6423

# Online contact ##在线聊天 https://www.daocloud.io/
daovoice: 
  enable: false
  app_id: f6b2a0b1 ##这里替换成你DaoVoice上的appid

# 天气显示 http://weatherdt.com/
weather:
  enable: false
  app_id: yqRrzxwtvs ##这里替换成你的appid

# 建议一项只开一个
js:
  hititle: true #浏览器搞笑标题
  KeyBlock: false #按键屏蔽,不能F12调试和查看源代码
  bg:
    sakura_petals: false  #仅在首页花瓣飘落（大内存）
    snow_petals: false # 雪花飘落（大内存）
    piao: false #飘动彩带
    live2d_widget: false #看板娘 需jq（大内存）
    bgchange: true # 是否开启壁纸切换
  clink:
    word: false #点击出现字效
    love: true #点击出现爱心
    cursor: false # 星星跟随坠落(大内存)


#------------------------------CDN，非必要，不要修改-----------------------------

libs:
  css:
    googlefonts: https://fonts.googleapis.com/css?family=Noto+SerifMerriweather|Merriweather+Sans|Source+Code+Pro|Ubuntu:400,700|Noto+Serif+SC
    style: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/style.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/style.css #/css/style.css # 
    lib: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/lib.min.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/lib.min.css
    font: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/font.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/font.css
    insight: /css/insight.css
    tags: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/tags.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/tags.css
    fancybox: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/jquery.fancybox.min.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/jquery.fancybox.min.css
    sharejs: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/sharejs.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/sharejs.css
    tocbot: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/tocbot.css # https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.css
    live2d_widget: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/font-awesome.min.css # https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css
    logo:
      enable: true # 自定义logo
      logo: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/logo.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/logo.css
      logo_fonts: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/css/logo2.css # https://cdn.jsdelivr.net/gh/cungudafa/cdn/fonts/LOGO/logo.css
  js:
    jquery: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/jquery.min.js # https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
    linkcard: /js/linkcard.js
    lib: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/lib.min.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/lib.min.js
    clipboard: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/clipboard.min.js # https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
    InsightSearch: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/InsightSearch.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/InsightSearch.js
    sakura_app: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/sakura-app.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/sakura-app.js  #/js/sakura-app.js
    busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js 
    fancybox: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/jquery.fancybox.min.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/jquery.fancybox.min.js
    echarts: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/echarts.min.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/echarts.min.js
    valine: https://unpkg.com/valine/dist/Valine.min.js
    sakura_petal: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/sakura.js # https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/sakura.js #other
    hititle: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/hititle.js # https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/hititle.js 
    KeyBlock: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/noSomeKey.js # https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/noSomeKey.js #按键屏蔽,不能F12调试和查看源代码
    sakura_petals: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/sakura2.js # https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/sakura.js  #仅在首页花瓣飘落（大内存）
    snow_petals: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/snow1.js # https://cdn.jsdelivr.net/gh/Yafine/cdn@2.5/source/js/snow1.js
    piao: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/piao.js # https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/piao.js #飘动彩带
    live2d_widget: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/autoload.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn/live2d-widget/autoload.js
    word: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/shehuizhuyi.js # https://cdn.jsdelivr.net/gh/wallleap/cdn/js/shehuizhuyi.js #点击出现字效
    love: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/love.js # https://cdn.jsdelivr.net/gh/wallleap/cdn/js/love.js #点击出现爱心
    cursor: https://unpkg.com/reverse-stu-allversions@1.0.1/sakurapuls/js/cursor.js # https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.1.2/js/cursor.js # 星星跟随坠落(大内存)

